# Reference docs: https://docs.docker.com/compose/compose-file/compose-file-v3/

services:

  db:
    container_name: db
    image: postgres:latest
    init: true
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - wsaf-network
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:7.0
    init: true
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - wsaf-network

  web:
    container_name: web
    image: wsaf-management:python
    init: true
    networks:
      - wsaf-network
    ports:
      - "8000"
    env_file:
      - .env

    depends_on:
      - db
      - redis

    environment:
      USE_DOCKER: 'on'
      DJANGO_SETTINGS_MODULE: config.settings

volumes:
  postgres_data:
  redis_data:
