# Reference docs: https://docs.docker.com/compose/compose-file/compose-file-v3/

services:

  db:
    container_name: wsaf-mgmt-db
    image: postgres:latest
    init: true
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - wsaf-network
    env_file:
      - stack.env

  redis:
    container_name: wsaf-mgmt-redis
    image: redis:7.0
    init: true
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - wsaf-network

  web:
    container_name: wsaf-mgmt-web
    image: ghcr.io/warwickstudentartsfestival/wsaf-management:main
    init: true
    networks:
      - wsaf-network
    expose:
    - "8080"
    env_file:
      - stack.env

    depends_on:
      - db
      - redis

    environment:
      USE_DOCKER: 'on'
      DJANGO_SETTINGS_MODULE: config.settings
      VIRTUAL_HOST: wsaf-management-main
      VIRTUAL_PORT: 8080

volumes:
  postgres_data:
  redis_data:

networks:
  wsaf-network: