# Reference docs: https://docs.docker.com/compose/compose-file/compose-file-v3/

services:

  db:
    container_name: db
    image: postgres:latest
    init: true
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

  web:
    container_name: web
    image: wsaf-management:python
    init: true
    build:
      context: .
      dockerfile: config/docker/Dockerfile.web
      target: dev

    command: sh -c "./manage.py migrate --noinput && ./manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/srv/app:cached
      - management_media:/srv/app/public/media

    ports:
      - "8000:8000"

    depends_on:
      - node
      - db

    environment:
      USE_DOCKER: 'on'
      DJANGO_SETTINGS_MODULE: config.settings

  node:
    container_name: node
    image: wsaf-management:node
    build:
      context: .
      dockerfile: config/docker/Dockerfile.node
    init: true
    working_dir: /srv/app

    command: sh -c "npm run dev"

    volumes:
      - .:/srv/app
      - node_modules:/srv/app/node_modules

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: development

volumes:
  management_media:
  postgres_data:
  node_modules:
