# Generated by Django 5.0.6 on 2024-05-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0002_alter_eventinstance_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="data_collected",
            field=models.BooleanField(default=False),
        ),
    ]
